---
title: Discurso de Graduación
author: Alberto Torrejón Valenzuela
date: '2020-03-21'
slug: discurso-de-graduacion
categories:
  - textos
tags:
  - Discurso
description: ''
---

<div class="just">
El 21 de marzo de 2020, durante el confinamiento escribí el que luego se convertiría en el discurso de graduación de la Promoción 2015/2020 del Doble GRado en Matemáticas y Estadística de la Universidad de Sevilla.

**21/03/2020:**

Este año es mi último año de carrera. Mis compañeros me dejaron escribir el discurso de fin de curso y leerlo en la graduación, algo que llevaba queriendo desde hace tiempo. Les dije que no sé lo enseñaría hasta que no llegase el día. Hoy que estaba algo cabizbajo lo he acabado y por lo que pueda pasar lo he querido compartir. Cuando todo esto pase, que pasará, lo leeré, nos reiremos y nos iremos de copas a celebrar.
</div>

**19/06/2021:**

<span class = "primerapalabra">M</span>ás de un año para esto. 

> *“Las universidades no crean tontos, solamente los desarrollan.”*
<div class="der">
<span class = "primerapalabra">George Horace Lorimer. </span>
</div>

<div class="just">
Estimado decano y componentes del equipo académico. Estimados padres, madres y demás familiares. Estimados compañeros, amigos. Hállome enchido de honor y honra de encontrarme hoy aquí ante todos ustedes en un día tan especial. Déjenme, ahora que todavía dispongo de su interés, que les introduzca una famosa paradoja griega:

> *Teseo, rey fundador de Atenas relata en una de sus historias un viaje en barco desde Creta hasta Atenas. Dicho barco tenía treinta remos, y los atenienses lo conservaban desde 300 años atrás, ya que retiraban las tablas estropeadas y las reemplazaban por unas nuevas y más resistentes.*

Toda aventura tiene un comienzo, la nuestra tiene lugar en este edificio, la Facultad de Matemáticas de la Universidad de Sevilla. Quizás estas paredes no nos hayan visto madurar en exceso, pero desde luego han sido testigo diario de nuestra perseverancia. Algunos, los que menos, se han enamorado (mirar a Paco), los que más, hemos blasfemado e incluso renegado de nuestras propias capacidades, y es que aquí hemos luchado contra nuestro peor enemigo, nosotros mismos, forjándonos al mismo tiempo en el delicado y potente menester de las matemáticas, y estadística. 

Recuerdo que los primeros días de clase, un profesor, viendo nuestras caras de desorientados, nos dijo: *“Nadie ha dicho que esto vaya a ser fácil, pero no preocuparos, ya pasaréis por el aro de las matemáticas”*. Esa frase que aquel día y para muchos cayó en el olvido, no podía ser más acertada. Estaréis de acuerdo en que todos hemos tenido ese momento en el que los teoremas, corolarios, demostraciones y problemas dejaron de ser un peso en nuestro equipaje para convertirse en aliados en nuestro camino. 

Toca agradecer. 

Decía **Mark Twain**: *“Cuando yo tenía catorce años, mis padres eran tan ignorantes que no podía soportarles. Pero cuando cumplí los veintiuno, me parecía increíble lo mucho que habían aprendido en siete años”.*  Papá, mamá, perdón y gracias. Perdón por nuestras constantes idas y venidas, malas caras y banales preocupaciones que en su momento significaban todo un mundo, y que vosotros, ávidos de bondad, habéis tratado como tales. A menudo olvidamos que vosotros también fuisteis jóvenes. Y gracias, porque sin vosotros esto no hubiese sido posible de ninguna de las formas.

Decía **Voltarie**: *“Hay alguien tan inteligente que aprende de la experiencia de los demás”.* Supongo que Voltaire querría referirse a sus profesores. A todos ellos, sin excepciones aunque con si con distintos niveles de gratitud, gracias, sigan abriendo caminos y motivando a insolentes alumnos tal y como lo han hecho con nosotros, pero no deben olvidar que estos insolentes de hoy seremos los que mañana defenderemos sus teorías, escuchen nuestras ganas, corríjanos cuando nos equivoquemos y perdonen nuestra arrogancia.

Por último, pero no menos importante, nosotros, vosotros. Se me hace raro no vernos entre apuntes en la facultad, tomando alguna que otra cerveza, o discutiendo sobre si en la pizarra pone “phi”, “theta”, o sobre para qué sirve exactamente lo que hay en la pizarra. Os felicito compañeros y deseo que todos podáis conseguir vuestros objetivos en el futuro. Vuestro sacrificio y esfuerzo, virtudes que os han hecho llegar hasta aquí, han sido para mí el reflejo de la importancia de compartir promoción con vosotros. La disciplina tarde o temprano vence a la inteligencia. No obstante, esto no ha de servir de alimento para el ego sino más bien debiera evocar la alta responsabilidad de saberse custodios de una gran responsabilidad en tiempos de incertidumbre, la capacidad de afrontar problemas que nadie quiere ni plantearse. La matemática es un arma, porque nos permite demostrar de forma inalienable, la estadística a su vez, nos permite respaldar con datos nuestras opiniones. Así, cuando intenten convencernos, vencernos-con, argumentos de dolor y miedo aferraos a los principios que nacieron con vosotros y no olvidéis que los comienzos que os formaron, son sólidos y extemporáneos.

¿Recuerdan la paradoja del principio?

> *Al final, tras tanto tiempo, el barco ya no se parecía al original, ninguna de las piezas del barco se correspondía con las primeras que se habían usado para construirlo. Pero, ¿seguía siendo el mismo barco?*

Las cosas cambian de nombre. El momento que ahora vivimos se llama pasado cuando está lejos, y cuando ya no está, se llama melancolía. Nuevas tablas cubrirán nuestros errores, nuevos remos nos harán mejorar, pero siempre, siempre, seremos el mismo barco. Ha sido un placer compartir esta andadura con vosotros compañeros, ahora un nuevo horizonte pide paso. 

</div>