---
title: Carta de amor
author: Alberto Torrejón Valenzuela
date: '2020-11-21'
categories:
  - textos
tags:
  - Amor
  - Textos
slug: texto-carta-de-amor
---


<center><h3>**Carta de amor**</h3></center>

<div class="just"> Querida... algo que ya dejaste de ser para convertirte en deseada, así que... </div>

<br>

<div class="just"> Amada **deseada**: </div>

<br>

<div class="just"> Hoy iba paseando y en un escaparate vi unos *Manolo Blahnik* beige, lisos, simples, pero increíblemente llamativos. Me acordé de tí. De como caminas descalza cuando los tacones te han ganado la partida, de la silueta de tu empeine y del perfil de tus piernas que deja obsoleta toda naturaleza. Poco después me encontré con unos robustos *Edward Green* de cordones, marrones, imagen de la arrogancia y seriedad que se nos imprime de pequeños a los hombres y de la que, aunque yo no suelo hacer gala, el resto de mis semejantes sí. </div>

<br>

<div class="just"> Ambos eran fantásticos, brillaban en sus respectivos escaparates, eran nuevos, con la suela sin desgastar. Me fascinaron y me acordé de nuestra relación, de nuestros viernes que acaban en domingo, de nuestras discusiones potencialmente intelectuales y de tus llantos que solo consigo calmar leyéndote a Machado. Sin embargo, al llegar a casa, en la entrada, estaban las viejas Converse que me regalaste cuando aun estábamos en el instituto, y lo comprendí, todo se tornó claro, no somos *Manolo Blahnik* ni *Edward Green*, somos el desgaste que el tiempo nos ha marcado, lo bonito ya no es lo nuevo sino lo cotidiano, no es lógico, es amor, un crimen de lesa humanidad que a todos nos debería llegar, y es que como decía Neruda: “la escogí a usted porque me di cuenta de que valía la pena, valía los riesgos, valía la vida”. </div>

<br>

<div class="just"> Siempre tuyo, </div>

<br>

<div class="just"> Alberto. </div>

<br>