---
title: Mensaje de Navidad 2020
author: Alberto Torrejón Valenzuela
date: '2020-12-25'
slug: mensaje-de-navidad-2020
categories:
  - textos
tags:
  - Mensaje
  - Navidad
  - Proverbio
description: ''
---

**A veces solo hay que parar**^[*Gracias por el consejo papá.*]

<span class = "primerapalabra">U</span>n terrateniente encargó a dos campesinos que segasen sus tierras. Cada uno empezaría a segar por un lado y el que antes terminase recibiría la mitad de las tierras para su disfrute como recompensa. Ambos se pusieron día y noche a segar. El primero lo hacía con ansia y rapidez, mientras que el segundo se tomaba su tiempo y disfrutaba. Un día, el segundo campesino paró a descansar, bebió agua y tomó la chaira con la que pudo afilar la hoja de su segadora. El primero, viendo que este se paraba a descansar, le dijo: “¡Qué tonto eres! ¡Mientras tú descansas yo trabajaré el doble de rápido y me haré con las tierras!” El segundo campesino se rio y una vez acabado su descanso prosiguió con su trabajo. Llegado el momento, la cuchilla del primero se rompió y no pudo acabar el trabajo mientras que el segundo pudo terminar y acabó haciéndose con las tierras prometidas.

A veces, cuando algo o alguien entra en tu vida y rompe tus esquemas basta solo con parar, rehacerse y seguir avanzando. Las montañas rusas, como la vida, dan vueltas, bajan y suben, a veces muy alto y otras muy bajo, pero siempre, siempre, avanzan hacia adelante.

Felices fiestas a todos y que este año traiga lo necesario para seguir avanzando. 

Atentamente,

<div class="der">
<span class = "primerapalabra">Alberto Torrejón Valenzuela</span>
</div>